---
- name: Download, Unpack and Deploy Energy website
  hosts: all 
  gather_facts: false

  vars: 
##
## Below are the required variables that needed to run successfully.
##
#    webarchive: [file name of zipfile that contains the website housed on GitHub:cyburdine/Windows-Demos/files] 
##
  tasks:
    - name: Print IP Address
      {% for host in groups['all'] %}
        {{ debug: var=hostvars[host]['ansible_eth0']['ipv4']['address'] }}
      {% endfor %}
    - name: Ensure website directory structure exists
      win_file:
        path: C:\sites\energy
        state: directory

    - name: Pull down website code from GitHub
      win_get_url:
        url: https://raw.githubusercontent.com/cyburdine/Windows-Demos/master/files/{{ webarchive }}
        dest: C:\sites\energy\{{ webarchive }}
        skip_certificate_validation: true
        force: true

    - name: Unpack website
      win_unzip:
       src: C:\sites\energy\{{ webarchive }}
       dest: C:\sites\energy\

    - name: Remove the website zip file, if present
      win_file:
        path: C:\sites\energy\{{ webarchive }}
        state: absent

    - name: Remove Default Web Site
      win_iis_website:
        name: "Default Web Site"
        state: absent

    - name: Setting up Energy IIS site
      win_iis_website:
        name: "Energy"
        state: started
        port: 80
        ip: 10.0.100.58
        application_pool: DefaultAppPool
        physical_path: c:\sites\energy\
        parameters: logfile.directory:c:\sites\logs
      register: website
