---
- name: Download, Unpack and Deploy Energy website
  hosts: all 
  gather_facts: false

  tasks:
    - name: Create directory structure
      win_file:
        path: C:\sites\energy
        state: directory

    - name: Setting up Energy IIS site
      win_iis_website:
        name: "Energy"
        state: started
        port: 80
        ip: 127.0.0.1
#       hostname: acme.local
        application_pool: "energy"
        physical_path: c:\sites\energy
        parameters: logfile.directory:c:\sites\logs
      register: website

    - name: Remove Default Web Site
      win_iis_website:
        name: "Default Web Site"
        state: absent

    - name: Download simple web site to 'C:\Windows\tmp\'
      win_get_url:
        url: 'https://raw.githubusercontent.com/cyburdine/Windows-Demos/master/files/energy_website_theme.zip'
        dest: 'C:\sites\energy'

    - name: Unpack Website
      win_unzip:
        src: C:\Windows\tmp\energy_website_theme.zip
        dest: C:\sites\energy\
