---
- name: Download, Unpack and Deploy Energy website
  hosts: all 
  gather_facts: false

  tasks:
    - name: Ensure website directory structure exists
      win_file:
        path: C:\sites\energy
        state: directory

    - name: Pull down website code from GitHub
      win_get_url:
        url: https://raw.githubusercontent.com/cyburdine/Windows-Demos/master/files/energy_website_theme.zip
        dest: C:\sites\energy\energy_website_theme.zip
        skip_certificate_validation: true
        force: true

    - name: Unpack website
      win_unzip:
       src: C:\sites\energy\energy_website_theme.zip
       dest: C:\sites\energy\

    - name: Remove the website zip file, if present
      win_file:
        path: C:\sites\energy\energy_website_theme.zip
        state: absent

    - name: Remove Default Web Site
      win_iis_website:
        name: "Default Web Site"
        state: absent

    - name: Setting up Energy IIS site
      win_iis_website:
        name: "Energy"
        state: started
        port: 80
        ip: 10.0.100.53
        application_pool: DefaultAppPool
        physical_path: c:\sites\energy\factory-html\
        parameters: logfile.directory:c:\sites\logs
      register: website
