---
- name: Enable / Disable IIS
  hosts: all
  gather_facts: false

  vars:
###
### The following vars must be set in order to run
###
#
#    iis_state: [present | absent]
#
###
  tasks:
    - name: Reconfiguring IIS
      win_feature:
        name: "Web-Server"
        state: "{{ iis_state }}"
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: Rebooting Server to finsh disabling IIS
      win_reboot:
        when: iis_state == "absent"
