- name: This Playbook provisions instances in vCenter
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
##
## Below are the variables that need to be set for this to run properly
##
#    vcenter_name: [ip/fqdn of vcenter]
#    vcenter_user: [vcenter user]
#    vcenter_pass: [vcenter password]
#    vm_name: [name of vm to be built]
#    vm_notes: This VM was provisioned by Ansible
#    disk1_size: [numerical value in GB]
#    disk1_type: [thin/thick]
#    disk1_datastore: [name of datastore
#    vm_folder: [path to the vcenter folder to be built in]
#    vm_template: [name of template to be cloned from]
#    vm_memory: [numerical value in MB]
#    vm_cpu: [numerical value for number of processors]
#    vm_osid: [vmware operating system id see vmware osid page for a list]
#    vm_datacenter: [name of the vcenter datacenter]
#    vm_hostname: [esxi host to place vm]
##

  tasks: 
  - name: Provisioning a VM
    vsphere_guest:
      vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      guest: "{{ vm_name }}"
      from_template: yes
      template_src: "{{ vm_template }}"
      vm_extra_config:
        notes: "{{ vm_notes }}"
        folder: "{{ vm_folder }}"
      vm_disk:
        disk1:
          size_gb: "{{ disk1_size }}"
          type: "{{ disk1_type }}"
          datastore: "{{ disk1_datastore }}"
      vm_nic:
        nic1:
          type: vmxnet3
          network: Backend
          network_type: standard
      vm_hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: "{{ vm_cpu }}"
        osid: "{{ vm_osid }}" 
        scsi: paravirtual
      esxi:
        datacenter: "{{ vm_datacenter }}"
        hostname: "{{ vm_hostname }}"

  - name: Wait for WinRM port to be open
    wait_for:
      host: "{{ ansible_host | default(inventory_hostname) }}"
      port: 5985
      delay: 15
      timeout: 600
