- name: Destroy Specified VMware Instance
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
##
## The following variables need to be set for this playbook to run
##
#    vcenter_name: [enter vcenter hostname]
#    vcenter_user: [enter username]
#    vcenter_pass: [enter password]
#    vm_name: [enter VM name]
##

  tasks: 
  - name: Destroy vCenter VM: "{{ vm_name }}"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_name }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      guest: "{{ vm_name }}"
      state: absent
      force: yes
