- name: get vmguest facts
  vsphere_guest:
    vmware_guest_facts: true
    vcenter_hostname: 172.16.32.2
    username: administrator
    password: "{{ Password }}"
    guest: jbWinVM-drift
    validate_certs: no
  register: vmguest_facts

- name: debug facts
  debug: >
    msg="vmguest facts are {{ vmguest_facts }}
    VM Name - {{ vmguest_facts.ansible_facts.hw_name }}
    CPU Count - {{ vmguest_facts.ansible_facts.hw_processor_count }}
    Memory Count - {{ vmguest_facts.ansible_facts.hw_memtotal_mb }}
    OS - {{ vmguest_facts.ansible_facts.hw_guest_full_name }}
    Power State - {{ vmguest_facts.ansible_facts.hw_power_status }}
    "
#    IP Addresses - {{ vmguest_facts.ansible_facts.ipaddresses.[1] }}
