- name: Posting to SNOW API
  uri:
    url: https://dev12140.service-now.com/api/now/table/incident
    user: "{{ Username }}"
    password: "{{ Password }}"
    method: POST
    return_content: no
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {"opened_by":"Ansible",
      "short_description":"{{ snow_short_description }}",
      "comments":"
        VM Hostname: {{ vm_hostname }}
        VM VMware Name: {{ vm_vmwarename }}
        VM IP Address: {{ vm_ipaddress }}
        ",
      "urgency":"{{ snow_urgency }}",
      "impact":"{{ snow_urgency }}",
      "priority":"{{ snow_urgency }}"}
    status_code: 201
    validate_certs: no
#  no_log: True
#  failed_when: false
